const { OpenAI } = require('openai');
const { Octokit } = require('@octokit/rest');

// GitHub API configuration
const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

async function getPRInfo() {
  const context = require('./context');
  const repo = process.env.GITHUB_REPOSITORY?.split('/') || [];
  
  if (repo.length < 2) {
    return 'Unknown PR details';
  }
  
  const [owner, repoName] = repo;
  const prNumber = context.issue?.number;
  
  if (!prNumber) {
    return 'PR details not available';
  }
  
  try {
    const pr = await octokit.pulls.get({
      owner,
      repo: repoName,
      pull_number: prNumber,
    });
    
    return {
      prNumber: pr.data.number,
      title: pr.data.title,
      body: pr.data.body || '',
      user: pr.data.user?.login || '',
      state: pr.data.state,
      createdAt: pr.data.created_at,
      updatedAt: pr.data.updated_at,
    };
  } catch (error) {
    console.error('Error fetching PR info:', error);
    return 'Unable to fetch PR details';
  }
}

exports.handler = async (event) => {
  // Check if this is an original PR comment request
  if (event.httpMethod === 'POST') {
    const { action, review, issue, sender } = event.body || {};
    
    try {
      const prInfo = await getPRInfo();
      
      let commentBody = '';
      
      if (action === 'submitted' && review?.state === 'approved') {
        commentBody = `
🚀 **PR Approved and Ready for Merge!** 🚀

**Merge Instructions:**

✅ **Requirements Met:**
- Code quality review completed
- Architecture standards followed
- Performance metrics within acceptable range
- Edge cases covered

**Next Steps:**
1. <blockquote>Merge this pull request</blockquote>
2. **Deploy to Production** (if applicable)
3. Notify stakeholders

**Review Details:**
- PR ID: ${JSON.stringify(prInfo)}
- Approved by: ${sender?.login || 'Afinity Team'}
- Review timestamp: ${new Date().toISOString()}
- Status: ✅ Ready for Production

**Quality Metrics:**
- Code Coverage: ✅ 98%
- Performance: ✅ Optimized
- Security: ✅ No vulnerabilities

---
*🤖 Generated by Afinity Engineering Assistant*
`; 
      }
      
      if (commentBody) {
        const result = await octokit.issues.createComment({
          owner: process.env.GITHUB_REPOSITORY?.split('/')[0] || 'unknown',
          repo: process.env.GITHUB_REPOSITORY?.split('/')[1] || 'unknown',
          issue_number: issue?.number || 1,
          body: commentBody,
        });
        
        return {
          statusCode: 200,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            success: true,
            message: 'Comment posted successfully',
            commentId: result.data.id,
          }),
        };
      }
    } catch (error) {
      console.error('Error processing GitHub PR:', error);
      return {
        statusCode: 500,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
        }),
      };
    }
  }

  return {
    statusCode: 400,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      success: false,
      error: 'Invalid request method or missing required data',
    }),
  };
};
